apiVersion: apps/v1
kind: Deployment
metadata:
  name: api

spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
          env:
          - name: DB
            value: "postgres://postgres:mY_seCret@postgres:5432/postgres"
